spring:
  profiles:
    active: dev
  shell.command:
    history.enabled: false
    script.enabled: false
shell:
  out:
    info: CYAN
    success: GREEN
    warning: YELLOW
    error: RED
---
logging:
  pattern:
    console:
spring.shell.command.stacktrace.enabled: false
spring:
  config:
    activate:
      on-profile: production
